export const LOGIN = 'login'
export const LOGIN_OUT = 'loginOut'
export const UPDATE_PLAY_INFO = 'updatePlayInfo'
export const ADD = 'addToList'
export const CLEAR = 'clearList'
export const GET_MUSIC = 'getMusic'
export const RESET_MUSIC = 'resetMusic'